### ISSUE TITLE
v1.0.5 - reappearance of en.ini problem - issue with flow renaming

### ISSUE THREAD

**Issue by burque505** [bichlepa/AutoHotFlow#4]
Issue: v1.0.5 requires manual configuration to start. Supplied AutoHotFlow.exe (32-bit?) cannot find gdiplus.dll (suspect side-by-side problem)
Steps to duplicate:
- Download source zip, extract
- Run AutoHotFlow.ahk as Administrator
     Error about en.ini;
     Error: can't find gdiplus.dll

Workaround one:
  -  Compile AutoHotFlow.ahk with 64-bit compiler
  -  copy 'en.ini' from older release to appropriate folder

Now 1.0.5 starts
Issue 2: Test flows do not run
Steps to duplicate:
- Run automatic tests
     Error as shown:

![image](https://user-images.githubusercontent.com/46876254/132989827-e75beec9-eca4-4609-8aca-1ee88f914c7a.png)

Suspected cause: renaming of Flow*** to Test Flow***

**Comment by bichlepa** [comment]
Thanks again for reporting!
I see, I broke the test flows. 🙈 

But I can't reproduce the other problems. I followed the steps that you described.
AutoHotFlow.ahk actually should start `find flows.ahk` on first start and it creates the merged translation files. I wonder why it happens on your PC.
On my PC there is no problem with gdiplus.dll. Actually `AutoHotFlow.ahk` does not use GDI+. It only starts main.ahk using AutoHotkey_H 32bit (which is now named as `AutoHotFlow.exe`, because it is then easier to find in the task manager). So recompiling `AutoHotFlow.ahk` can't possibly have resolved the GDI+ problem. It seems to have solved itself randomly.

Btw the binaries `AutoHotFlow Setup.exe`, `AutoHotFlow.exe` and `find modules.exe` are not meant to be in the repository, I removed them yesterday. In the zip of v1.0.5 they are existing and broken and should not be used.

**Comment by bichlepa** [comment]
Does the problem still exist?

**Comment by burque505** [comment]
I haven't checked for several days, I can try to reinstall in another directory.
I will report back.
EDIT: The en.ini problem is gone, I will close that issue. Thank you!

**Comment by burque505** [comment]
Closed 2021-09-17
en.ini problem resolved.
